sudo: required
services:
  - docker

before_install:
  - docker build -t rtdocker -f Dockerfile.dev .

script:
  - docker run -e CI=true rtdocker npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "rtdocker-apk"
  env: "Rtdockerapk-env"
  bucket_name: "elasticbeanstalk-us-east-1-684343307429"
  bucket_path: "rtdocker-apk" 
  on:
    branch: master
